spring:
  application:
    name: trombone-master

  datasource:
    url: jdbc:postgresql://localhost:5432/trombone_master
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

springdoc:
  swagger-ui:
    url: /openapi/openapi.yaml